name: Build client
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build client
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        branch: ['master', 'dev', 'release_19.09', 'release_20.01']
    steps:
      - uses: actions/checkout@v2
      - name: Clone Galaxy
        run: git clone --depth=1 -b ${{ matrix.branch }}  https://github.com/galaxyproject/galaxy
      - name: Check if client build exists
        id: tag
        run: echo "::set-output name=tag_exists::$(git ls-remote --tags | grep ${{ matrix.branch }}-$(cd galaxy && git rev-parse HEAD 2>/dev/null))"
      - name: show tag
        run: echo "${{ steps.tag.outpus.tag_exists }}"
      - name: Build client
        if: steps.tag.outpus.tag_exists == ''
        run: yarn install --network-timeout 300000 --check-files && yarn run build
        working-directory: ./galaxy/client
      - name: Archive client
        if: steps.tag.outpus.tag_exists == ''
        run: | 
          mv galaxy/static .
          git config --global user.name 'mvdbeek'
          git config --global user.email 'mvdbeek@users.noreply.github.com'
          git add static
          git commit -m "Build client for Galaxy branch ${{ matrix.branch }}, commit $(cd galaxy && git rev-parse HEAD 2>/dev/null))"
          git tag ${{ matrix.branch }}-$(git rev-parse HEAD 2>/dev/null)
          git push origin ${{ matrix.branch }}-$(git rev-parse HEAD 2>/dev/null)
